const result = {
  Order: {
    Address: {
      Street: "75 East Liberty",
      StreetNumber: "75",
      StreetName: "EAST LIBERTY ST",
      UnitType: "",
      UnitNumber: "",
      City: "Toronto",
      Region: "ON",
      PostalCode: "M6K 3R3",
      DeliveryInstructions: "",
      CountyName: null,
      CountyNumber: null,
    },
    AmountsBreakdown: {
      foodAndBeverage: "13.99",
      adjustment: "0.00",
      surcharge: "0.00",
      deliveryFee: "5.50",
      tax: 0,
      tax1: 0,
      tax2: 0,
      tax3: 0,
      tax4: 0,
      tax5: 0,
      bottle: 0,
      customer: 19.49,
      roundingAdjustment: 0,
      cash: 0,
      savings: "0.00",
    },
    BusinessDate: "2024-12-24",
    Coupons: [],
    Currency: "CAD",
    CustomerID: "",
    EstimatedWaitMinutes: "10-20",
    Email: "michaelwasihun96@gmail.com",
    Extension: "",
    FirstName: "Michael",
    HotspotsLite: false,
    IP: "134.231.56.45",
    LastName: "Shimeles",
    LanguageCode: "en",
    Market: "CANADA",
    NewUser: true,
    NoCombine: true,
    OrderChannel: "OLO",
    OrderID: "0zc5H2E1SW8RQ-qSy1k1",
    OrderInfoCollection: [],
    OrderMethod: "Web",
    OrderTaker: "node-dominos-pizza-api",
    Partners: {},
    Payments: [
      {
        Type: "CreditCard",
        Amount: 0,
        TipAmount: 0,
        Number: "4100123422343234",
        CardType: "VISA",
        Expiration: "0135",
        SecurityCode: "867",
        PostalCode: "93940",
      },
    ],
    Phone: "4168397968",
    PhonePrefix: "",
    PriceOrderMs: 621,
    PriceOrderTime: "2024-12-24 09:57:53",
    Products: [
      {
        ID: 1,
        Code: "16SCREEN",
        Qty: 1,
        CategoryCode: "Pizza",
        FlavorCode: "HANDTOSS",
        LikeProductID: 0,
        Name: '16" Hand Tossed ',
        NeedsCustomization: false,
        AutoRemove: false,
        Fulfilled: false,
        SideOptions: [],
        Tags: {},
        Descriptions: [
          {
            portionCode: "1/1",
            value: "Pizza Sauce, Mozzarella Cheese",
          },
        ],
        Amount: 13.99,
        isNew: true,
        Status: 0,
        Price: 13.99,
      },
    ],
    Promotions: { redeemable: [], availablePromos: {}, Redeemable: [] },
    PulseOrderGuid: "",
    ServiceMethod: "Delivery",
    SourceOrganizationURI: "order.dominos.ca",
    StoreID: "10526",
    Tags: {},
    UserAgent: "",
    Version: "1.0",
    UnitNumber: "1507",
    UnitType: "Condo",
    PricingFlag: "0",
    metaData: { calculateNutrition: true, contactless: true },
    DpzSourceHeader: "DSSPlaceOrder",
    Status: -1,
    StatusItems: [
      { Code: "PriceInformationRemoved" },
      {
        Code: "PosOrderIncomplete",
        PulseCode: 6,
        PulseText: "Amount paid is insufficient.",
      },
      { Code: "StoreClosed" },
    ],
    Amounts: {
      Menu: 19.49,
      Discount: 0,
      Surcharge: 5.5,
      DeliveryFee: 5.5,
      Adjustment: 0,
      Net: 19.49,
      Tax: 0,
      Tax1: 0,
      Tax2: 0,
      Bottle: 0,
      Customer: 19.49,
      Payment: 19.49,
      RoundingAdjustment: 0,
    },
  },
  Status: -1,
  Offer: { CouponList: [], ProductOffer: "" },
  EmailHash: null,
  DeviceId: "9f72297442c76ce8275a3820482eb691d28dcab606e74d49b8f3eb8b5bfe45e0",
  NeedsInStoreProcessing: false,
  StatusItems: [{ Code: "Failure" }],
};
